//TODO ESTE CODIGO DE ESTE METODO ES CAPAZ DE DIRECCIONAR A LOS USUARIOS A LAS PAGINAS DE LOS PRODUCTO HACIENDO QUE NUESTRO CLIENTES SEAN CAPACES DE COMPRAR NUESTROS PRODUCTO Y HACER QUE TODOS NUESTROS EMPLEADOS PUEDAN COMER
function clic_prod(prod){
    location.href = "PRODUCTO_" + prod + ".html"
}
